[project]
name = "da-ekf-troute"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopandas>=1.1.4",
    "numba>=0.67.0",
    "numpy==1.26.4",
    "nwmurl>=1.0.7",
    "pandas==2.2.0",
    "requests>=2.34.2",
    "scipy>=1.17.1",
    "xarray<2026.7.0",
    "setuptools==68.2.2"
]
